version: '3.8'

services:
  camera-app:
    container_name: camera-app
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./storage:/storage/backup
    devices:
      # Map the host USB bus directory to the container so libgphoto2 can scan and interact with the PTP bus
      - /dev/bus/usb:/dev/bus/usb
    restart: "no" # Control lifecycle strictly via udev rules (hotplug start/stop)
